/* Automatically generated by
	SmartSyntaxPluginCodeGenerator VMMaker-eem.666 uuid: 4edd7d00-3db5-48ef-b579-5d95fae49120
   from
	QPlatformEventPlugin Qwaq-Plugins-jcg.108 uuid: be07d71f-9c53-4c06-8e16-66431a11bfe4
 */
static char __buildInfo[] = "QPlatformEventPlugin Qwaq-Plugins-jcg.108 uuid: be07d71f-9c53-4c06-8e16-66431a11bfe4 " __DATE__ ;




#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Default EXPORT macro that does nothing (see comment in sq.h): */
#define EXPORT(returnType) returnType

/* Do not include the entire sq.h file but just those parts needed. */
/*  The virtual machine proxy definition */
#include "sqVirtualMachine.h"
/* Configuration options */
#include "sqConfig.h"
/* Platform specific definitions */
#include "sqPlatformSpecific.h"

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
#undef EXPORT
// was #undef EXPORT(returnType) but screws NorCroft cc
#define EXPORT(returnType) static returnType
#endif
#include "QPlatformEventPlugin.h"

#include "sqMemoryAccess.h"


/*** Constants ***/


/*** Function Prototypes ***/
static VirtualMachine * getInterpreter(void);
EXPORT(const char*) getModuleName(void);
static sqInt halt(void);
EXPORT(sqInt) initialiseModule(void);
static sqInt msg(char *s);
EXPORT(sqInt) primitiveCreateFeedbackChannel(void);
EXPORT(sqInt) primitiveDestroyFeedbackChannel(void);
EXPORT(sqInt) primitiveFeedbackChannelPopEvent(void);
EXPORT(sqInt) primitiveFeedbackChannelReadEvent(void);
EXPORT(sqInt) primitiveFeedbackChannelSetLogging(void);
EXPORT(sqInt) primitiveSqueakStringFromCPlusPlus(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine*anInterpreter);
EXPORT(sqInt) shutdownModule(void);
static void sqAssert(sqInt aBool);


/*** Variables ***/

#ifdef SQUEAK_BUILTIN_PLUGIN
extern
#endif
struct VirtualMachine* interpreterProxy;
static const char *moduleName =
#ifdef SQUEAK_BUILTIN_PLUGIN
	"QPlatformEventPlugin Qwaq-Plugins-jcg.108 (i)"
#else
	"QPlatformEventPlugin Qwaq-Plugins-jcg.108 (e)"
#endif
;



/*	Note: This is coded so that plugins can be run from Squeak. */

static VirtualMachine *
getInterpreter(void) {
	return interpreterProxy;
}


/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

EXPORT(const char*)
getModuleName(void) {
	return moduleName;
}

static sqInt
halt(void) {
	;
	return 0;
}

EXPORT(sqInt)
initialiseModule(void) {
	qInitModule();
	return 1;
}

static sqInt
msg(char *s) {
	fprintf(stderr, "\n%s: %s", moduleName, s);
	return 0;
}


/*	Create a C++ FeedbackChannel object; stash a pointer to it in
	'externalAddress'. Answer 0 for success and a negative value for errors.
	If unsuccessful, the contents of 'externalAddress' will be unchanged. */

EXPORT(sqInt)
primitiveCreateFeedbackChannel(void) {
	sqInt result;
	char *externalAddress;
	sqInt semaphoreIndex;
	sqInt _return_value;

	interpreterProxy->success(interpreterProxy->isBytes(interpreterProxy->stackValue(1)));
	externalAddress = ((char *) (interpreterProxy->firstIndexableField(interpreterProxy->stackValue(1))));
	semaphoreIndex = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	result = qCreateFeedbackChannel(externalAddress, semaphoreIndex);
	_return_value = interpreterProxy->integerObjectOf(result);
	if (interpreterProxy->failed()) {
		return null;
	}
	interpreterProxy->popthenPush(3, _return_value);
	return null;
}


/*	Destroy a C++ FeedbackChannel object. */

EXPORT(sqInt)
primitiveDestroyFeedbackChannel(void) {
	char *externalAddress;

	interpreterProxy->success(interpreterProxy->isBytes(interpreterProxy->stackValue(0)));
	externalAddress = ((char *) (interpreterProxy->firstIndexableField(interpreterProxy->stackValue(0))));
	if (interpreterProxy->failed()) {
		return null;
	}
	qDestroyFeedbackChannel(externalAddress);
	if (interpreterProxy->failed()) {
		return null;
	}
	interpreterProxy->pop(1);
	return null;
}


/*	Pop the frontmost event from the channel identified by 'externalAddress'. */

EXPORT(sqInt)
primitiveFeedbackChannelPopEvent(void) {
	char *externalAddress;

	interpreterProxy->success(interpreterProxy->isBytes(interpreterProxy->stackValue(0)));
	externalAddress = ((char *) (interpreterProxy->firstIndexableField(interpreterProxy->stackValue(0))));
	if (interpreterProxy->failed()) {
		return null;
	}
	qFeedbackChannelPopEvent(externalAddress);
	if (interpreterProxy->failed()) {
		return null;
	}
	interpreterProxy->pop(1);
	return null;
}


/*	Answer a newly-instantiated ByteArray describing the channel's next event,
	or nil if there is no next event (and also if the address is invalid).
	Note that the event stays in the channel until it is released via
	#primitiveFeedbackChannelPopEvent:. 
 */

EXPORT(sqInt)
primitiveFeedbackChannelReadEvent(void) {
	sqInt resultOop;
	char *externalAddress;

	interpreterProxy->success(interpreterProxy->isBytes(interpreterProxy->stackValue(0)));
	externalAddress = ((char *) (interpreterProxy->firstIndexableField(interpreterProxy->stackValue(0))));
	if (interpreterProxy->failed()) {
		return null;
	}
	resultOop = qFeedbackChannelReadEvent(externalAddress);
	if (interpreterProxy->failed()) {
		return null;
	}
	interpreterProxy->popthenPush(2, resultOop);
	return null;
}


/*	Turn logging on or off for the specified channel. */

EXPORT(sqInt)
primitiveFeedbackChannelSetLogging(void) {
	char *externalAddress;
	sqInt trueOrFalse;

	interpreterProxy->success(interpreterProxy->isBytes(interpreterProxy->stackValue(1)));
	externalAddress = ((char *) (interpreterProxy->firstIndexableField(interpreterProxy->stackValue(1))));
	trueOrFalse = interpreterProxy->booleanValueOf(interpreterProxy->stackValue(0));
	if (interpreterProxy->failed()) {
		return null;
	}
	qFeedbackChannelSetLogging(externalAddress, trueOrFalse);
	if (interpreterProxy->failed()) {
		return null;
	}
	interpreterProxy->pop(2);
	return null;
}


/*	'ptr' points to a C++ std::string; instantiate a Squeak string with the
	same contents.
 */

EXPORT(sqInt)
primitiveSqueakStringFromCPlusPlus(void) {
	sqInt stringLength;
	sqInt stringPtr;
	sqInt squeakStringPtr;
	sqInt squeakString;
	char *ptr;

	interpreterProxy->success(interpreterProxy->isBytes(interpreterProxy->stackValue(0)));
	ptr = ((char *) (interpreterProxy->firstIndexableField(interpreterProxy->stackValue(0))));
	if (interpreterProxy->failed()) {
		return null;
	}
	stringLength = stdStringLength(ptr);
	stringPtr = stdStringCStr(ptr);
	squeakString = interpreterProxy->instantiateClassindexableSize(interpreterProxy->classString(), stringLength);
	if (!(interpreterProxy->failed())) {
		squeakStringPtr = interpreterProxy->firstIndexableField(squeakString);
		memcpy(squeakStringPtr, stringPtr, stringLength);
	}
	if (interpreterProxy->failed()) {
		return null;
	}
	interpreterProxy->popthenPush(2, squeakString);
	return null;
}


/*	Note: This is coded so that is can be run from Squeak. */

EXPORT(sqInt)
setInterpreter(struct VirtualMachine*anInterpreter) {
	sqInt ok;

	interpreterProxy = anInterpreter;
	ok = interpreterProxy->majorVersion() == VM_PROXY_MAJOR;
	if (ok == 0) {
		return 0;
	}
	ok = interpreterProxy->minorVersion() >= VM_PROXY_MINOR;
	return ok;
}

EXPORT(sqInt)
shutdownModule(void) {
	qShutdownModule();
	return 1;
}

static void
sqAssert(sqInt aBool) {
	/* missing DebugCode */;
}


#ifdef SQUEAK_BUILTIN_PLUGIN

void* QPlatformEventPlugin_exports[][3] = {
	{"QPlatformEventPlugin", "getModuleName", (void*)getModuleName},
	{"QPlatformEventPlugin", "initialiseModule", (void*)initialiseModule},
	{"QPlatformEventPlugin", "primitiveCreateFeedbackChannel", (void*)primitiveCreateFeedbackChannel},
	{"QPlatformEventPlugin", "primitiveDestroyFeedbackChannel", (void*)primitiveDestroyFeedbackChannel},
	{"QPlatformEventPlugin", "primitiveFeedbackChannelPopEvent", (void*)primitiveFeedbackChannelPopEvent},
	{"QPlatformEventPlugin", "primitiveFeedbackChannelReadEvent", (void*)primitiveFeedbackChannelReadEvent},
	{"QPlatformEventPlugin", "primitiveFeedbackChannelSetLogging", (void*)primitiveFeedbackChannelSetLogging},
	{"QPlatformEventPlugin", "primitiveSqueakStringFromCPlusPlus", (void*)primitiveSqueakStringFromCPlusPlus},
	{"QPlatformEventPlugin", "setInterpreter", (void*)setInterpreter},
	{"QPlatformEventPlugin", "shutdownModule", (void*)shutdownModule},
	{NULL, NULL, NULL}
};

#endif /* ifdef SQ_BUILTIN_PLUGIN */
