/* isql OpenQwaqData UserId UserPass -b < OpenQwaqData.sql  */
/* NOTE: isql is pathetic; everything must be single line, sorry! */
CREATE TABLE IF NOT EXISTS users (id CHAR(36) NOT NULL, name VARCHAR(100) NOT NULL, email VARCHAR(100) NOT NULL, status VARCHAR(50) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, company VARCHAR(100) NOT NULL, files VARCHAR(255) NOT NULL, sfdc_id VARCHAR(50) NOT NULL, created DATETIME NOT NULL, comment VARCHAR(255) NOT NULL, PRIMARY KEY (id, name)) Engine=InnoDB;
CREATE TABLE IF NOT EXISTS organizations (id CHAR(36) NOT NULL, name VARCHAR(100) NOT NULL, seats INTEGER UNSIGNED NOT NULL, tier VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, creator_id CHAR(36) NOT NULL, files VARCHAR(255) NOT NULL, server VARCHAR(100) NOT NULL, sfdc_id VARCHAR(50) NOT NULL, created DATETIME NOT NULL, expires DATETIME, comment VARCHAR(255) NOT NULL, PRIMARY KEY (id)) Engine=InnoDB;
CREATE TABLE IF NOT EXISTS user_accounts (id CHAR(36) NOT NULL, status VARCHAR(50) NOT NULL, org_name VARCHAR(100) NOT NULL, user_name VARCHAR(100) NOT NULL, role_name VARCHAR(50) NOT NULL, org_id CHAR(36) NOT NULL, user_id CHAR(36) NOT NULL, sfdc_id VARCHAR(50) NOT NULL, created DATETIME NOT NULL, comment VARCHAR(255) NOT NULL, PRIMARY KEY (id)) Engine=InnoDB;
CREATE TABLE IF NOT EXISTS user_passwords (id INTEGER UNSIGNED NOT NULL DEFAULT NULL AUTO_INCREMENT, name VARCHAR(100) NOT NULL, password VARCHAR(100) NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id, name)) Engine=InnoDB;
CREATE TABLE IF NOT EXISTS user_digests ( id INTEGER UNSIGNED NOT NULL DEFAULT NULL AUTO_INCREMENT, name VARCHAR(100) NOT NULL, digest CHAR(36) NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY (id, name)) Engine = InnoDB;
CREATE TABLE IF NOT EXISTS servers (id INTEGER NOT NULL DEFAULT NULL AUTO_INCREMENT, pool VARCHAR(100) NOT NULL, role VARCHAR(100) NOT NULL, status VARCHAR(100) NOT NULL, internal_name VARCHAR(100) NOT NULL, external_name VARCHAR(100) NOT NULL, created DATETIME NOT NULL, PRIMARY KEY (id)) Engine=InnoDB;
/* New tables for qfes 2.0: groups, org_members, group_members */
CREATE TABLE IF NOT EXISTS groups (id CHAR(36) NOT NULL, name VARCHAR(100) NOT NULL, status VARCHAR(50) NOT NULL, created DATETIME NOT NULL, comment VARCHAR(255) NOT NULL, PRIMARY KEY (id)) Engine=InnoDB;
CREATE TABLE IF NOT EXISTS org_members (id CHAR(36) NOT NULL, status VARCHAR(50) NOT NULL, org_name VARCHAR(100) NOT NULL, org_id CHAR(36) NOT NULL, member_name VARCHAR(100) NOT NULL, member_id CHAR(36) NOT NULL, member_type VARCHAR(100) NOT NULL, role_name VARCHAR(50) NOT NULL, sfdc_id VARCHAR(50) NOT NULL, created DATETIME NOT NULL, comment VARCHAR(255) NOT NULL, PRIMARY KEY (id)) Engine=InnoDB;
CREATE TABLE IF NOT EXISTS group_members (id CHAR(36) NOT NULL, status VARCHAR(50) NOT NULL, group_name VARCHAR(100) NOT NULL, group_id CHAR(36) NOT NULL, member_name VARCHAR(100) NOT NULL, member_id CHAR(36) NOT NULL, member_type VARCHAR(100) NOT NULL, created DATETIME NOT NULL, comment VARCHAR(255) NOT NULL, PRIMARY KEY (id)) Engine=InnoDB;
/* Convert the old user_accounts to org_members */
INSERT INTO org_members select id, status, org_name, org_id, user_name, user_id, "user", role_name, sfdc_id, created, comment from user_accounts where id not in (select id from org_members);
