/* Automatically generated by
	VMPluginCodeGenerator VMMaker-jcg.607 uuid: fdb55ec9-1ef0-4f02-b610-6d8f9068ae8d
   from
	SipPlugin Qwaq-Plugins-jcg.108 uuid: be07d71f-9c53-4c06-8e16-66431a11bfe4
 */
static char __buildInfo[] = "SipPlugin Qwaq-Plugins-jcg.108 uuid: be07d71f-9c53-4c06-8e16-66431a11bfe4 " __DATE__ ;




#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Default EXPORT macro that does nothing (see comment in sq.h): */
#define EXPORT(returnType) returnType

/* Do not include the entire sq.h file but just those parts needed. */
/*  The virtual machine proxy definition */
#include "sqVirtualMachine.h"
/* Configuration options */
#include "sqConfig.h"
/* Platform specific definitions */
#include "sqPlatformSpecific.h"

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
#undef EXPORT
// was #undef EXPORT(returnType) but screws NorCroft cc
#define EXPORT(returnType) static returnType
#endif
#include "SipPlugin.h"

#include "sqMemoryAccess.h"


/*** Constants ***/


/*** Function Prototypes ***/
static VirtualMachine * getInterpreter(void);
EXPORT(const char*) getModuleName(void);
static sqInt halt(void);
EXPORT(sqInt) initialiseModule(void);
static sqInt msg(char *s);
EXPORT(sqInt) primitiveFakeREGISTER(void);
EXPORT(sqInt) primitiveProcessDUM(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine*anInterpreter);
EXPORT(sqInt) shutdownModule(void);


/*** Variables ***/

#ifdef SQUEAK_BUILTIN_PLUGIN
extern
#endif
struct VirtualMachine* interpreterProxy;
static const char *moduleName =
#ifdef SQUEAK_BUILTIN_PLUGIN
	"SipPlugin Qwaq-Plugins-jcg.108 (i)"
#else
	"SipPlugin Qwaq-Plugins-jcg.108 (e)"
#endif
;



/*	Note: This is coded so that plugins can be run from Squeak. */

static VirtualMachine *
getInterpreter(void) {
	return interpreterProxy;
}


/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

EXPORT(const char*)
getModuleName(void) {
	return moduleName;
}

static sqInt
halt(void) {
	;
	return 0;
}

EXPORT(sqInt)
initialiseModule(void) {
	return qInitModule();
}

static sqInt
msg(char *s) {
	fprintf(stderr, "\n%s: %s", moduleName, s);
	return 0;
}


/*	Give DUM a chance to process any events from the SIP stack. */

EXPORT(sqInt)
primitiveFakeREGISTER(void) {
	qFakeREGISTER();
	return null;
}


/*	Give DUM a chance to process any events from the SIP stack. */

EXPORT(sqInt)
primitiveProcessDUM(void) {
	qProcessDUM();
	return null;
}


/*	Note: This is coded so that is can be run from Squeak. */

EXPORT(sqInt)
setInterpreter(struct VirtualMachine*anInterpreter) {
    sqInt ok;

	interpreterProxy = anInterpreter;
	ok = interpreterProxy->majorVersion() == VM_PROXY_MAJOR;
	if (ok == 0) {
		return 0;
	}
	ok = interpreterProxy->minorVersion() >= VM_PROXY_MINOR;
	return ok;
}

EXPORT(sqInt)
shutdownModule(void) {
	return qShutdownModule();
}


#ifdef SQUEAK_BUILTIN_PLUGIN

void* SipPlugin_exports[][3] = {
	{"SipPlugin", "getModuleName", (void*)getModuleName},
	{"SipPlugin", "initialiseModule", (void*)initialiseModule},
	{"SipPlugin", "primitiveFakeREGISTER", (void*)primitiveFakeREGISTER},
	{"SipPlugin", "primitiveProcessDUM", (void*)primitiveProcessDUM},
	{"SipPlugin", "setInterpreter", (void*)setInterpreter},
	{"SipPlugin", "shutdownModule", (void*)shutdownModule},
	{NULL, NULL, NULL}
};

#endif /* ifdef SQ_BUILTIN_PLUGIN */
