#!/bin/bash
# Build a "complete" Mac VM consisting of CoreVM + Plugins.
BUILD_CONFIGURATION=Deployment
KEEP=

USAGE="usage: `basename $0` -[dkh?]"

while getopts 'dkh?' opt $@; do
	case $opt in
	d)		BUILD_CONFIGURATION=Development;;
	k)		KEEP=1;;
	h|\?|*)	echo $USAGE
			echo '	build the vm (defaults to a Deployment version)'
			echo '  -d: compile a Development version for debugging'
			echo '  -k: keep (do not delete) the existing Teleplace.app prior to the build'
			echo '	-h: display this help'
			exit 0;;
	esac
done

test "$KEEP" = 1 || rm -rf Teleplace.app

# Build CoreVM using xcode
echo
echo CoreVM xcodebuild -project CoreVM.xcodeproj -configuration $BUILD_CONFIGURATION
xcodebuild -project CoreVM.xcodeproj -configuration $BUILD_CONFIGURATION
mv build/$BUILD_CONFIGURATION/Teleplace.app .

# Copy private frameworks.
# Note that we prune the copies of the media-codec frameworks, leaving only the single numbered part.
# (Eliminating the top-level link, and the Current link)
(cd resources; tar cf - --exclude Current  --exclude .svn Frameworks) | (cd Teleplace.app/Contents; tar xf -)

# Build the PyBridge
echo
echo PyBridge xcodebuild -project PyBridge/PyBridge.xcodeproj -configuration Release
xcodebuild -project PyBridge/PyBridge.xcodeproj -configuration Release
cp -R PyBridge/build/Release/PyBridge.bundle Teleplace.app/Contents/Resources


# Update PyBridge to use private Python framework
install_name_tool -id \
  @executable_path/../Frameworks/Python \
  Teleplace.app/Contents/Frameworks/Python
install_name_tool -change \
  /Library/Frameworks/Python.framework/Versions/2.4/Python \
  @executable_path/../Frameworks/Python \
  Teleplace.app/Contents/Resources/PyBridge.bundle/Contents/MacOS/PyBridge

# Copy private frameworks.
# Note that we prune the copies of the media-codec frameworks, leaving only the single numbered part.
# (Eliminating the top-level link, and the Current link)
(cd resources; tar cf - --exclude Current  --exclude .svn Frameworks) | (cd Teleplace.app/Contents; tar xf -)

# Build the Webcam plugin
echo
echo QWebcamPlugin xcodebuild -project plugin-projects/QWebcamPlugin/QWebcamPlugin.xcodeproj -configuration Release
xcodebuild -project plugin-projects/QWebcamPlugin/QWebcamPlugin.xcodeproj -configuration Release
cp -R plugin-projects/QWebcamPlugin/build/Release/QWebcamPlugin.bundle Teleplace.app/Contents/Resources

# Build the PNG plugin
xcodebuild -project PNGLibPlugin/PNGLibPlugin.xcodeproj -configuration Release
cp -R PNGLibPlugin/build/Release/PNGLibPlugin.bundle Teleplace.app/Contents/Resources

# Build the codec plugin
# (This uses MainConcept frameworks.)
xcodebuild -project QVideoCodecPluginMC/QVideoCodecPluginMC.xcodeproj -configuration Release
cp -R QVideoCodecPluginMC/build/Release/QVideoCodecPluginMC.bundle Teleplace.app/Contents/Resources

#Build the Float plugin
echo
echo FloatMathPlugin xcodebuild -project FloatMathPlugin/FloatMathPlugin.xcodeproj -configuration Release
xcodebuild -project FloatMathPlugin/FloatMathPlugin.xcodeproj -configuration Release
cp -R FloatMathPlugin/build/Release/FloatMathPlugin.bundle Teleplace.app/Contents/Resources

#Build the FloatArray plugin
echo
echo FloatArrayPlugin xcodebuild -project FloatArrayPlugin/FloatArrayPlugin.xcodeproj -configuration Release
xcodebuild -project FloatArrayPlugin/FloatArrayPlugin.xcodeproj -configuration Release
cp -R FloatArrayPlugin/build/Release/FloatArrayPlugin.bundle Teleplace.app/Contents/Resources

#Build the Croquet plugin
echo
echo CroquetPlugin xcodebuild -project CroquetPlugin/CroquetPlugin.xcodeproj -configuration Release
xcodebuild -project CroquetPlugin/CroquetPlugin.xcodeproj -configuration Release
cp -R CroquetPlugin/build/Release/CroquetPlugin.bundle Teleplace.app/Contents/Resources

# Build the FFI plugin (New as of 27 March 2008)
echo
echo SqueakFFIPlugin xcodebuild -project SqueakFFIPrims/SqueakFFI.xcodeproj -configuration Deployment
xcodebuild -project SqueakFFIPrims/SqueakFFI.xcodeproj -configuration Deployment
cp -R SqueakFFIPrims/build/Deployment/SqueakFFIPrims.bundle Teleplace.app/Contents/Resources

# Build the Audio plugin (New as of 13 May 2008)
# XXXXX: For some reason, the Release version builds, but doesn't work.
#        I looked carefully at all of the project settings, and still
#        couldn't figure out why.
echo
echo AudioPlugin xcodebuild -project plugin-projects/QAudioPlugin/QAudioPlugin.xcodeproj -configuration Release
xcodebuild -project plugin-projects/QAudioPlugin/QAudioPlugin.xcodeproj -configuration Release
cp -R plugin-projects/QAudioPlugin/build/Release/QAudioPlugin.bundle Teleplace.app/Contents/Resources

# Build the Mpeg3Plugin plugin
echo
echo Mpeg3Plugin xcodebuild -project Mpeg3Plugin/Mpeg3Plugin.xcodeproj -configuration Deployment
xcodebuild -project Mpeg3Plugin/Mpeg3Plugin.xcodeproj -configuration Deployment
cp -R Mpeg3Plugin/build/Deployment/Mpeg3Plugin.bundle Teleplace.app/Contents/Resources

# Build the PSharePlugin
echo
echo PSharePlugin xcodebuild -project plugin-projects/PSharePlugin/PSharePlugin.xcodeproj -configuration Release
xcodebuild -project plugin-projects/PSharePlugin/PSharePlugin.xcodeproj -configuration Release
cp -R plugin-projects/PSharePlugin/build/Release/PSharePlugin.bundle Teleplace.app/Contents/Resources

# Build the WebAuthPlugin (New as of 28 April 2010)
echo
echo WebAuthPlugin xcodebuild -project WebAuthPlugin/WebAuthPlugin.xcodeproj -configuration Deployment
xcodebuild -project WebAuthPlugin/WebAuthPlugin.xcodeproj -configuration Deployment
cp -R WebAuthPlugin/build/Release/WebAuthPlugin.bundle Teleplace.app/Contents/Resources


# The following plugins should be built but right now we only copy them
#  (Note that SqueakFFIPrims has been removed from this list... but there's an old copy in resources)
# cp -R resources/Mpeg3Plugin.bundle Teleplace.app/Contents/Resources

# Build the UnixOSProcessPlugin
echo UnixOSProcessPlugin xcodebuild -configuration Release -project UnixOSProcessPlugin/UnixOSProcessPlugin.xcodeproj
xcodebuild -configuration Release -project UnixOSProcessPlugin/UnixOSProcessPlugin.xcodeproj
cp -R UnixOSProcessPlugin/build/Release/UnixOSProcessPlugin.bundle Teleplace.app/Contents/Resources

# Copy OpenAL.framework since the current one is broken
# No!  This is fully supported on 10.4+, and part of the core platform.
# Now that we have - the squeak sound option, and only MacIntel support,
# there's no need to bundle a custom (and early poor quality) build of this.
#
# cp -R resources/OpenAL.framework Teleplace.app/Contents/Resources

# Clean out any .svn directories (result of copying) in the VM
find Teleplace.app -name .svn -exec rm -rf {} \;
