#!/bin/sh
D=
A=
F=
H=
while [ -n "$1" ]; do
	case $1 in
	-A|-AS)	D=LOGGD;A=LOGGA;F=LOGGS;;
	-d)	D=LOGGD;;
	-a)	A=LOGGA;;
	-f)	F=LOGGF;;
	-?|-h)	H=h
	esac
	shift
done
if [ -n "$H" -o -z "$D$A$F" ]; then
	echo usage: $0 -A \| -AS \| -d -a -f
	exit
fi
test -n "$D" && (mymakevm-gcc -d 2>&1 | tee $D;grep "BUILD .*ED" $D)
test -n "$A" && (mymakevm-gcc -a 2>&1 | tee $A;grep "BUILD .*ED" $A)
test -n "$F" && (mymakevm-gcc -s 2>&1 | tee $F;grep "BUILD .*ED" $F)

test -n "$D" && (echo $D;grep "BUILD .*ED" $D)
test -n "$A" && (echo $A;grep "BUILD .*ED" $A)
test -n "$F" && (echo $F;grep "BUILD .*ED" $F)
