/**
 * Project OpenQwaq
 *
 * Copyright (c) 2005-20011, Teleplace, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-2.0.php.
 *
 */

/*
 * QVideoCodecPlugin.h
 * QVideoCodecPlugin
 *
 * Function declarations needed by the C-code generated by 
 * QVideoCodecPlugin (and its API-specific subclasses).
 */

#ifndef __Q_VIDEO_CODEC_PLUGIN_H__
#define __Q_VIDEO_CODEC_PLUGIN_H__

#include "qVideoEncoder.h"
#include "qVideoDecoder.h"
#include "qVideoCommon.h"

#endif //#ifndef __Q_VIDEO_CODEC_PLUGIN_H__
