/* Automatically generated by
	VMPluginCodeGenerator VMMaker-eem.529 uuid: 784f5163-06ea-4e67-b7ff-9604209cec92
   from
	FileDialogPlugin Qwaq-Plugins-eem.104 uuid: b9506c9c-87dc-4678-ac96-1e40a495a0ea
 */
static char __buildInfo[] = "FileDialogPlugin Qwaq-Plugins-eem.104 uuid: b9506c9c-87dc-4678-ac96-1e40a495a0ea " __DATE__ ;




#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Default EXPORT macro that does nothing (see comment in sq.h): */
#define EXPORT(returnType) returnType

/* Do not include the entire sq.h file but just those parts needed. */
/*  The virtual machine proxy definition */
#include "sqVirtualMachine.h"
/* Configuration options */
#include "sqConfig.h"
/* Platform specific definitions */
#include "sqPlatformSpecific.h"

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
#undef EXPORT
// was #undef EXPORT(returnType) but screws NorCroft cc
#define EXPORT(returnType) static returnType
#endif
#include "FileDialogPlugin.h"

#include "sqMemoryAccess.h"



/*** Constants ***/


/*** Function Prototypes ***/
static VirtualMachine * getInterpreter(void);
EXPORT(const char*) getModuleName(void);
static sqInt halt(void);
EXPORT(sqInt) initialiseModule(void);
static sqInt msg(char *s);
static sqInt oopFromString(char*cString);
EXPORT(sqInt) primitiveFileDialogAddFilter(void);
EXPORT(sqInt) primitiveFileDialogCallbackReturn(void);
EXPORT(sqInt) primitiveFileDialogCreate(void);
EXPORT(sqInt) primitiveFileDialogDestroy(void);
EXPORT(sqInt) primitiveFileDialogDone(void);
EXPORT(sqInt) primitiveFileDialogDoneSemaphore(void);
EXPORT(sqInt) primitiveFileDialogGetFilterIndex(void);
EXPORT(sqInt) primitiveFileDialogGetResult(void);
EXPORT(sqInt) primitiveFileDialogSetCallbackSemaphore(void);
EXPORT(sqInt) primitiveFileDialogSetFile(void);
EXPORT(sqInt) primitiveFileDialogSetFilterIndex(void);
EXPORT(sqInt) primitiveFileDialogSetLabel(void);
EXPORT(sqInt) primitiveFileDialogSetProperty(void);
EXPORT(sqInt) primitiveFileDialogShow(void);
EXPORT(sqInt) primitiveGetFileLocation(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine*anInterpreter);
static sqInt stackBooleanValue(sqInt index);
static sqInt stackDialogHandle(sqInt index);
static void * stackStringValue(sqInt index);


/*** Variables ***/

#ifdef SQUEAK_BUILTIN_PLUGIN
extern
#endif
struct VirtualMachine* interpreterProxy;
static const char *moduleName =
#ifdef SQUEAK_BUILTIN_PLUGIN
	"FileDialogPlugin Qwaq-Plugins-eem.104 (i)"
#else
	"FileDialogPlugin Qwaq-Plugins-eem.104 (e)"
#endif
;



/*	Note: This is coded so that plugins can be run from Squeak. */

static VirtualMachine *
getInterpreter(void) {
	return interpreterProxy;
}


/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

EXPORT(const char*)
getModuleName(void) {
	return moduleName;
}

static sqInt
halt(void) {
	;
	return 0;
}

EXPORT(sqInt)
initialiseModule(void) {
	return fileDialogInitialize();
}

static sqInt
msg(char *s) {
	fprintf(stderr, "\n%s: %s", moduleName, s);
	return 0;
}

static sqInt
oopFromString(char*cString) {
    char*dstPtr;
    sqInt i;
    sqInt result;
    sqInt sz;

	if (cString == null) {
		return interpreterProxy->nilObject();
	}
	sz = strlen(cString);
	result = interpreterProxy->instantiateClassindexableSize(interpreterProxy->classString(), sz);
	dstPtr = interpreterProxy->firstIndexableField(result);
	for (i = 0; i <= (sz - 1); i += 1) {
		dstPtr[i] = (cString[i]);
	}
	return result;
}


/*	Primitive. Add a filter to an existing file dialog.
	Arguments:
	dlgHandle: Handle for the file dialog.
	filterDesc: Description for the filter ('Text Files (*.txt)')
	filterPattern: Filter pattern (*.txt)
	Returns: Nothing. */

EXPORT(sqInt)
primitiveFileDialogAddFilter(void) {
    sqInt dlgHandle;
    char*filterDesc;
    char*filterPattern;

	if (!((interpreterProxy->methodArgumentCount()) == 3)) {
		return interpreterProxy->primitiveFail();
	}
	filterPattern = stackStringValue(0);
	filterDesc = stackStringValue(1);
	dlgHandle = interpreterProxy->positive32BitValueOf(interpreterProxy->stackValue(2));
	if (interpreterProxy->failed()) {
		if (filterDesc == null) {
			null;
		}
		else {
			free(filterDesc);
		}
		if (filterPattern == null) {
			null;
		}
		else {
			free(filterPattern);
		}
		return null;
	}
	fileDialogAddFilter(dlgHandle, filterDesc, filterPattern);
	free(filterDesc);
	free(filterPattern);
	interpreterProxy->pop(interpreterProxy->methodArgumentCount());
}


/*	Primitive. Set the callback semaphore to be used for running modal
	dialogs. 
 */

EXPORT(sqInt)
primitiveFileDialogCallbackReturn(void) {
	if (!((interpreterProxy->methodArgumentCount()) == 0)) {
		return interpreterProxy->primitiveFail();
	}
	fileDialogCallbackReturn();
}


/*	Primitive. Create a new file dialog handle and answer the result.
	Arguments: None.
	Return value: File dialog handle. */

EXPORT(sqInt)
primitiveFileDialogCreate(void) {
    sqInt dlgHandle;

	if (!((interpreterProxy->methodArgumentCount()) == 0)) {
		return interpreterProxy->primitiveFail();
	}
	dlgHandle = fileDialogCreate();
	if (dlgHandle == -1) {
		return interpreterProxy->primitiveFail();
	}
	interpreterProxy->pop((interpreterProxy->methodArgumentCount()) + 1);
	interpreterProxy->push(interpreterProxy->positive32BitIntegerFor(dlgHandle));
}


/*	Primitive. Hide/destroy the file dialog after it is done.
	Arguments:
	dlgHandle: Handle of the file dialog.
	Return value: Nothing.
	Notes: This primitive may fail if the dialog wasn't completed and platform
	doesn't support destroying existing dialogs. Generally it is assumed that
	the dialog has been closed by the user before calling this method. */

EXPORT(sqInt)
primitiveFileDialogDestroy(void) {
    sqInt dlgHandle;
    sqInt ok;

	if (!((interpreterProxy->methodArgumentCount()) == 1)) {
		return interpreterProxy->primitiveFail();
	}
	dlgHandle = interpreterProxy->positive32BitValueOf(interpreterProxy->stackValue(0));
	if (interpreterProxy->failed()) {
		return null;
	}
	ok = fileDialogDestroy(dlgHandle);
	if (!(ok)) {
		return interpreterProxy->primitiveFail();
	}
	interpreterProxy->pop(interpreterProxy->methodArgumentCount());
}


/*	Primitive. Answer whether the file dialog completed or not.
	Arguments:
	dlgHandle: Handle of the file dialog.
	Return value: Boolean indicating whether the dialog completed. */

EXPORT(sqInt)
primitiveFileDialogDone(void) {
    sqInt dlgHandle;
    sqInt done;

	if (!((interpreterProxy->methodArgumentCount()) == 1)) {
		return interpreterProxy->primitiveFail();
	}
	dlgHandle = interpreterProxy->positive32BitValueOf(interpreterProxy->stackValue(0));
	if (interpreterProxy->failed()) {
		return null;
	}
	done = fileDialogDone(dlgHandle);
	interpreterProxy->pop((interpreterProxy->methodArgumentCount()) + 1);
	interpreterProxy->pushBool(done);
}


/*	Primitive. Set the semaphore to be signaled when the file dialog
	completes. Arguments:
	dlgHandle:	Handle of the file dialog.
	semaIndex:	External semaphore index.
	Return value: Nothing. */

EXPORT(sqInt)
primitiveFileDialogDoneSemaphore(void) {
    sqInt dlgHandle;
    sqInt semaIndex;

	if (!((interpreterProxy->methodArgumentCount()) == 2)) {
		return interpreterProxy->primitiveFail();
	}
	semaIndex = interpreterProxy->stackIntegerValue(0);
	dlgHandle = interpreterProxy->positive32BitValueOf(interpreterProxy->stackValue(1));
	if (interpreterProxy->failed()) {
		return null;
	}
	fileDialogDoneSemaphore(dlgHandle, semaIndex);
	interpreterProxy->pop(interpreterProxy->methodArgumentCount());
}


/*	Primitive. Get the current filter index from one of the previously chosen
	filters. Arguments:
	dlgHandle: Handle for the file dialog.
	Return value: Filter index. */

EXPORT(sqInt)
primitiveFileDialogGetFilterIndex(void) {
    sqInt dlgHandle;
    sqInt result;

	if (!((interpreterProxy->methodArgumentCount()) == 1)) {
		return interpreterProxy->primitiveFail();
	}
	dlgHandle = interpreterProxy->positive32BitValueOf(interpreterProxy->stackValue(0));
	if (interpreterProxy->failed()) {
		return null;
	}
	result = fileDialogGetFilterIndex(dlgHandle);
	if (result == 0) {
		return interpreterProxy->primitiveFail();
	}
	interpreterProxy->pop((interpreterProxy->methodArgumentCount()) + 1);
	interpreterProxy->pushInteger(result);
}


/*	Primitive. Retrieve the result of the file dialog.
	Arguments:
	dlgHandle:	Handle of the file dialog.
	Return value: String for choosen file, or nil if canceled */

EXPORT(sqInt)
primitiveFileDialogGetResult(void) {
    char*cString;
    sqInt dlgHandle;
    sqInt result;

	if (!((interpreterProxy->methodArgumentCount()) == 1)) {
		return interpreterProxy->primitiveFail();
	}
	dlgHandle = interpreterProxy->positive32BitValueOf(interpreterProxy->stackValue(0));
	if (interpreterProxy->failed()) {
		return null;
	}
	cString = fileDialogGetResult(dlgHandle);
	if (interpreterProxy->failed()) {
		return null;
	}
	result = oopFromString(cString);
	interpreterProxy->pop((interpreterProxy->methodArgumentCount()) + 1);
	interpreterProxy->push(result);
}


/*	Primitive. Set the callback semaphore to be used for running modal
	dialogs. 
 */

EXPORT(sqInt)
primitiveFileDialogSetCallbackSemaphore(void) {
    sqInt semaIndex;

	if (!((interpreterProxy->methodArgumentCount()) == 1)) {
		return interpreterProxy->primitiveFail();
	}
	semaIndex = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	fileDialogSetCallbackSemaphore(semaIndex);
	interpreterProxy->pop(interpreterProxy->methodArgumentCount());
}


/*	Primitive. Set the initial file name/path for the dialog.
	Arguments:
	dlgHandle: Handle for the file dialog.
	filePath: Initial path for open dialog
	Returns: Nothing. */

EXPORT(sqInt)
primitiveFileDialogSetFile(void) {
    sqInt dlgHandle;
    char*filePath;

	if (!((interpreterProxy->methodArgumentCount()) == 2)) {
		return interpreterProxy->primitiveFail();
	}
	filePath = stackStringValue(0);
	dlgHandle = interpreterProxy->positive32BitValueOf(interpreterProxy->stackValue(1));
	if (interpreterProxy->failed()) {
		if (filePath == null) {
			null;
		}
		else {
			free(filePath);
		}
		return null;
	}
	fileDialogSetFile(dlgHandle, filePath);
	free(filePath);
	interpreterProxy->pop(interpreterProxy->methodArgumentCount());
}


/*	Primitive. Set the current filter index from one of the previously chosen
	filters. Arguments:
	dlgHandle: Handle for the file dialog.
	index: Current filter index.
	Return value: Nothing. */

EXPORT(sqInt)
primitiveFileDialogSetFilterIndex(void) {
    sqInt dlgHandle;
    sqInt index;

	if (!((interpreterProxy->methodArgumentCount()) == 2)) {
		return interpreterProxy->primitiveFail();
	}
	index = interpreterProxy->stackIntegerValue(0);
	dlgHandle = interpreterProxy->positive32BitValueOf(interpreterProxy->stackValue(1));
	if (interpreterProxy->failed()) {
		return null;
	}
	fileDialogSetFilterIndex(dlgHandle, index);
	interpreterProxy->pop(interpreterProxy->methodArgumentCount());
}


/*	Primitive. Set the label for the dialog.
	Arguments:
	dlgHandle: Handle for the file dialog.
	dlgLabel: Dialog label.
	Returns: Nothing. */

EXPORT(sqInt)
primitiveFileDialogSetLabel(void) {
    sqInt dlgHandle;
    char*dlgLabel;

	if (!((interpreterProxy->methodArgumentCount()) == 2)) {
		return interpreterProxy->primitiveFail();
	}
	dlgLabel = stackStringValue(0);
	dlgHandle = interpreterProxy->positive32BitValueOf(interpreterProxy->stackValue(1));
	if (interpreterProxy->failed()) {
		if (dlgLabel == null) {
			null;
		}
		else {
			free(dlgLabel);
		}
		return null;
	}
	fileDialogSetLabel(dlgHandle, dlgLabel);
	free(dlgLabel);
	interpreterProxy->pop(interpreterProxy->methodArgumentCount());
}


/*	Primitive. Set additional properties for a file dialog.
	Arguments:
	dlgHandle:	Handle of the file dialog.
	propName:	Property name.
	propValue: Boolean indication whether to turn it on or off.
	Return value: Boolean, indicating whether the property is supported. */

EXPORT(sqInt)
primitiveFileDialogSetProperty(void) {
    sqInt dlgHandle;
    sqInt ok;
    char*propName;
    sqInt propValue;

	if (!((interpreterProxy->methodArgumentCount()) == 3)) {
		return interpreterProxy->primitiveFail();
	}
	propValue = interpreterProxy->booleanValueOf(interpreterProxy->stackValue(0));
	propName = stackStringValue(1);
	dlgHandle = interpreterProxy->positive32BitValueOf(interpreterProxy->stackValue(2));
	if (interpreterProxy->failed()) {
		if (propName == null) {
			null;
		}
		else {
			free(propName);
		}
		return null;
	}
	ok = fileDialogSetProperty(dlgHandle, propName, propValue);
	free(propName);
	interpreterProxy->pop((interpreterProxy->methodArgumentCount()) + 1);
	interpreterProxy->pushBool(ok);
}


/*	Primitive. Show the file dialog.
	Arguments:
	dlgHandle:	Handle of the file dialog.
	fSaveAs:	Whether to show an 'open' or a 'save' style dialog.
	Return value: Nothing. */

EXPORT(sqInt)
primitiveFileDialogShow(void) {
    sqInt dlgHandle;
    sqInt fSaveAs;
    sqInt ok;

	if (!((interpreterProxy->methodArgumentCount()) == 2)) {
		return interpreterProxy->primitiveFail();
	}
	fSaveAs = interpreterProxy->booleanValueOf(interpreterProxy->stackValue(0));
	dlgHandle = interpreterProxy->positive32BitValueOf(interpreterProxy->stackValue(1));
	if (interpreterProxy->failed()) {
		return null;
	}
	ok = fileDialogShow(dlgHandle, fSaveAs);
	if (!(ok)) {
		return interpreterProxy->primitiveFail();
	}
	interpreterProxy->pop(interpreterProxy->methodArgumentCount());
}


/*	Primitive. Query for a common file location.
	Arguments:
	location: String describing the common file location.
	Return value: The path to the designated location.
	Known locations:
	'home' - the user's home directory
	'desktop' - the user's desktop directory
	
	'temp' - the temp directory to use
	'preferences' - the place to store (per user) app preferences
	'applications' - the directory for installing applications
	'fonts' - the directory to install fonts in the system
	
	'documents' - the users documents folder
	'music' - the users default location for music
	'pictures' - the users default location for pictures
	'videos' - the users default location for videos
	 */

EXPORT(sqInt)
primitiveGetFileLocation(void) {
    char*cString;
    char*location;
    sqInt result;

	if (!((interpreterProxy->methodArgumentCount()) == 1)) {
		return interpreterProxy->primitiveFail();
	}
	location = stackStringValue(0);
	if (interpreterProxy->failed()) {
		if (location == null) {
			null;
		}
		else {
			free(location);
		}
		return null;
	}
	cString = fileDialogGetLocation(location);
	if (cString == 0) {
		if (location == null) {
			null;
		}
		else {
			free(location);
		}
		return interpreterProxy->primitiveFail();
	}
	result = oopFromString(cString);
	free(location);
	interpreterProxy->popthenPush((interpreterProxy->methodArgumentCount()) + 1, result);
}


/*	Note: This is coded so that is can be run from Squeak. */

EXPORT(sqInt)
setInterpreter(struct VirtualMachine*anInterpreter) {
    sqInt ok;

	interpreterProxy = anInterpreter;
	ok = interpreterProxy->majorVersion() == VM_PROXY_MAJOR;
	if (ok == 0) {
		return 0;
	}
	ok = interpreterProxy->minorVersion() >= VM_PROXY_MINOR;
	return ok;
}

static sqInt
stackBooleanValue(sqInt index) {
	return interpreterProxy->booleanValueOf(interpreterProxy->stackValue(index));
}

static sqInt
stackDialogHandle(sqInt index) {
	return interpreterProxy->positive32BitValueOf(interpreterProxy->stackValue(index));
}

static void *
stackStringValue(sqInt index) {
    char*dstPtr;
    sqInt i;
    sqInt obj;
    char*srcPtr;
    sqInt sz;

	obj = interpreterProxy->stackValue(index);
	if (!(interpreterProxy->isBytes(obj))) {
		interpreterProxy->primitiveFail();
		return null;
	}
	sz = interpreterProxy->byteSizeOf(obj);
	dstPtr = malloc(sz + 1);
	srcPtr = interpreterProxy->firstIndexableField(obj);
	for (i = 0; i <= (sz - 1); i += 1) {
		dstPtr[i] = (srcPtr[i]);
	}
	dstPtr[sz] = 0;
	return dstPtr;
}


#ifdef SQUEAK_BUILTIN_PLUGIN

void* FileDialogPlugin_exports[][3] = {
	{"FileDialogPlugin", "getModuleName", (void*)getModuleName},
	{"FileDialogPlugin", "initialiseModule", (void*)initialiseModule},
	{"FileDialogPlugin", "primitiveFileDialogAddFilter", (void*)primitiveFileDialogAddFilter},
	{"FileDialogPlugin", "primitiveFileDialogCallbackReturn", (void*)primitiveFileDialogCallbackReturn},
	{"FileDialogPlugin", "primitiveFileDialogCreate", (void*)primitiveFileDialogCreate},
	{"FileDialogPlugin", "primitiveFileDialogDestroy", (void*)primitiveFileDialogDestroy},
	{"FileDialogPlugin", "primitiveFileDialogDone", (void*)primitiveFileDialogDone},
	{"FileDialogPlugin", "primitiveFileDialogDoneSemaphore", (void*)primitiveFileDialogDoneSemaphore},
	{"FileDialogPlugin", "primitiveFileDialogGetFilterIndex", (void*)primitiveFileDialogGetFilterIndex},
	{"FileDialogPlugin", "primitiveFileDialogGetResult", (void*)primitiveFileDialogGetResult},
	{"FileDialogPlugin", "primitiveFileDialogSetCallbackSemaphore", (void*)primitiveFileDialogSetCallbackSemaphore},
	{"FileDialogPlugin", "primitiveFileDialogSetFile", (void*)primitiveFileDialogSetFile},
	{"FileDialogPlugin", "primitiveFileDialogSetFilterIndex", (void*)primitiveFileDialogSetFilterIndex},
	{"FileDialogPlugin", "primitiveFileDialogSetLabel", (void*)primitiveFileDialogSetLabel},
	{"FileDialogPlugin", "primitiveFileDialogSetProperty", (void*)primitiveFileDialogSetProperty},
	{"FileDialogPlugin", "primitiveFileDialogShow", (void*)primitiveFileDialogShow},
	{"FileDialogPlugin", "primitiveGetFileLocation", (void*)primitiveGetFileLocation},
	{"FileDialogPlugin", "setInterpreter", (void*)setInterpreter},
	{NULL, NULL, NULL}
};

#endif /* ifdef SQ_BUILTIN_PLUGIN */
