/* Automatically generated by
	VMPluginCodeGenerator VMMaker-eem.524 uuid: 9b748596-0986-4ca7-ac5b-b7a050a08431
   from
	NativeFontPlugin Qwaq-Plugins-bgf.97 uuid: 15a615ba-3290-40a1-877d-f025b25fd3af
 */
static char __buildInfo[] = "NativeFontPlugin Qwaq-Plugins-bgf.97 uuid: 15a615ba-3290-40a1-877d-f025b25fd3af " __DATE__ ;




#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Default EXPORT macro that does nothing (see comment in sq.h): */
#define EXPORT(returnType) returnType

/* Do not include the entire sq.h file but just those parts needed. */
/*  The virtual machine proxy definition */
#include "sqVirtualMachine.h"
/* Configuration options */
#include "sqConfig.h"
/* Platform specific definitions */
#include "sqPlatformSpecific.h"

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
#undef EXPORT
// was #undef EXPORT(returnType) but screws NorCroft cc
#define EXPORT(returnType) static returnType
#endif
#include "NativeFontPlugin.h"

#include "sqMemoryAccess.h"



/*** Constants ***/


/*** Function Prototypes ***/
static VirtualMachine * getInterpreter(void);
EXPORT(const char*) getModuleName(void);
static sqInt halt(void);
EXPORT(sqInt) initialiseModule(void);
static sqInt msg(char *s);
EXPORT(sqInt) primitiveCreateFont(void);
EXPORT(sqInt) primitiveDestroyFont(void);
EXPORT(sqInt) primitiveFontAscent(void);
EXPORT(sqInt) primitiveFontDataSize(void);
EXPORT(sqInt) primitiveFontDescent(void);
EXPORT(sqInt) primitiveFontEmbeddingFlags(void);
EXPORT(sqInt) primitiveFontEncoding(void);
EXPORT(sqInt) primitiveFontFullWidthOfChar(void);
EXPORT(sqInt) primitiveFontGetKernPair(void);
EXPORT(sqInt) primitiveFontGlyphOfChar(void);
EXPORT(sqInt) primitiveFontNumKernPairs(void);
EXPORT(sqInt) primitiveFontWidthOfChar(void);
EXPORT(sqInt) primitiveGetFontData(void);
EXPORT(sqInt) primitiveListFont(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine*anInterpreter);
EXPORT(sqInt) shutdownModule(void);


/*** Variables ***/

#ifdef SQUEAK_BUILTIN_PLUGIN
extern
#endif
struct VirtualMachine* interpreterProxy;
static const char *moduleName =
#ifdef SQUEAK_BUILTIN_PLUGIN
	"NativeFontPlugin Qwaq-Plugins-bgf.97 (i)"
#else
	"NativeFontPlugin Qwaq-Plugins-bgf.97 (e)"
#endif
;



/*	Note: This is coded so that plugins can be run from Squeak. */

static VirtualMachine *
getInterpreter(void) {
	return interpreterProxy;
}


/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

EXPORT(const char*)
getModuleName(void) {
	return moduleName;
}

static sqInt
halt(void) {
	;
	return 0;
}


/*	Initialize the module */

EXPORT(sqInt)
initialiseModule(void) {
	return ioFontInit();
}

static sqInt
msg(char *s) {
	fprintf(stderr, "\n%s: %s", moduleName, s);
	return 0;
}

EXPORT(sqInt)
primitiveCreateFont(void) {
    sqInt fontFlags;
    sqInt fontID;
    sqInt fontName;
    sqInt fontNameIndex;
    sqInt fontNameLength;
    sqInt fontSize;

	if (!((interpreterProxy->methodArgumentCount()) == 3)) {
		return interpreterProxy->primitiveFail();
	}
	fontFlags = interpreterProxy->stackIntegerValue(0);
	fontSize = interpreterProxy->stackIntegerValue(1);
	fontName = interpreterProxy->stackObjectValue(2);
	if (interpreterProxy->failed()) {
		return null;
	}
	if (!(interpreterProxy->isBytes(fontName))) {
		return interpreterProxy->primitiveFail();
	}
	fontNameLength = interpreterProxy->byteSizeOf(fontName);
	fontNameIndex = ((int) (interpreterProxy->firstIndexableField(fontName)));
	fontID = ioCreateFont(fontNameIndex, fontNameLength, fontSize, fontFlags);
	if (fontID < 0) {
		return interpreterProxy->primitiveFail();
	}
	interpreterProxy->pop(4);
	interpreterProxy->pushInteger(fontID);
}

EXPORT(sqInt)
primitiveDestroyFont(void) {
    sqInt fontIndex;

	if (!((interpreterProxy->methodArgumentCount()) == 1)) {
		return interpreterProxy->primitiveFail();
	}
	fontIndex = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	if (!(ioDestroyFont(fontIndex))) {
		return interpreterProxy->primitiveFail();
	}
	return interpreterProxy->pop(1);
}

EXPORT(sqInt)
primitiveFontAscent(void) {
    sqInt ascent;
    sqInt fontIndex;

	if (!((interpreterProxy->methodArgumentCount()) == 1)) {
		return interpreterProxy->primitiveFail();
	}
	fontIndex = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	ascent = ioFontAscent(fontIndex);
	if (!(ascent >= 0)) {
		return interpreterProxy->primitiveFail();
	}
	interpreterProxy->pop(2);
	return interpreterProxy->pushInteger(ascent);
}

EXPORT(sqInt)
primitiveFontDataSize(void) {
    sqInt fontIndex;
    sqInt size;

	if (!((interpreterProxy->methodArgumentCount()) == 1)) {
		return interpreterProxy->primitiveFail();
	}
	fontIndex = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	size = ioGetFontDataSize(fontIndex);
	interpreterProxy->pop(2);
	return interpreterProxy->pushInteger(size);
}

EXPORT(sqInt)
primitiveFontDescent(void) {
    sqInt descent;
    sqInt fontIndex;

	if (!((interpreterProxy->methodArgumentCount()) == 1)) {
		return interpreterProxy->primitiveFail();
	}
	fontIndex = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	descent = ioFontDescent(fontIndex);
	if (!(descent >= 0)) {
		return interpreterProxy->primitiveFail();
	}
	interpreterProxy->pop(2);
	return interpreterProxy->pushInteger(descent);
}

EXPORT(sqInt)
primitiveFontEmbeddingFlags(void) {
    sqInt flags;
    sqInt fontIndex;

	if (!((interpreterProxy->methodArgumentCount()) == 1)) {
		return interpreterProxy->primitiveFail();
	}
	fontIndex = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	flags = ioFontEmbeddingFlags(fontIndex);
	interpreterProxy->pop(2);
	return interpreterProxy->pushInteger(flags);
}

EXPORT(sqInt)
primitiveFontEncoding(void) {
    sqInt encoding;
    sqInt fontIndex;

	if (!((interpreterProxy->methodArgumentCount()) == 1)) {
		return interpreterProxy->primitiveFail();
	}
	fontIndex = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	encoding = ioFontEncoding(fontIndex);
	if (!(encoding >= 0)) {
		return interpreterProxy->primitiveFail();
	}
	interpreterProxy->pop(2);
	return interpreterProxy->pushInteger(encoding);
}

EXPORT(sqInt)
primitiveFontFullWidthOfChar(void) {
    sqInt array;
    sqInt charIndex;
    sqInt fontIndex;
    int fullWidth[3];
    sqInt i;

	if (!((interpreterProxy->methodArgumentCount()) == 2)) {
		return interpreterProxy->primitiveFail();
	}
	charIndex = interpreterProxy->stackIntegerValue(0);
	fontIndex = interpreterProxy->stackIntegerValue(1);
	if (interpreterProxy->failed()) {
		return null;
	}
	if (!(ioFontFullWidthOfChar(fontIndex, charIndex, fullWidth))) {
		return interpreterProxy->primitiveFail();
	}
	array = interpreterProxy->instantiateClassindexableSize(interpreterProxy->classArray(), 3);
	for (i = 0; i <= 2; i += 1) {
		interpreterProxy->storeIntegerofObjectwithValue(i, array, fullWidth[i]);
	}
	interpreterProxy->pop(3);
	return interpreterProxy->push(array);
}

EXPORT(sqInt)
primitiveFontGetKernPair(void) {
    sqInt array;
    sqInt fontIndex;
    sqInt i;
    sqInt kernIndex;
    int kernPair[3];

	if (!((interpreterProxy->methodArgumentCount()) == 2)) {
		return interpreterProxy->primitiveFail();
	}
	kernIndex = interpreterProxy->stackIntegerValue(0);
	fontIndex = interpreterProxy->stackIntegerValue(1);
	if (interpreterProxy->failed()) {
		return null;
	}
	if (!(ioFontGetKernPair(fontIndex, kernIndex, kernPair))) {
		return interpreterProxy->primitiveFail();
	}
	array = interpreterProxy->instantiateClassindexableSize(interpreterProxy->classArray(), 3);
	for (i = 0; i <= 2; i += 1) {
		interpreterProxy->storeIntegerofObjectwithValue(i, array, kernPair[i]);
	}
	interpreterProxy->pop(3);
	return interpreterProxy->push(array);
}

EXPORT(sqInt)
primitiveFontGlyphOfChar(void) {
    sqInt charIndex;
    sqInt fontIndex;
    sqInt formBits;
    sqInt formDepth;
    sqInt formHeight;
    sqInt formOop;
    sqInt formWidth;
    sqInt pitch;
    sqInt ppw;

	if (!((interpreterProxy->methodArgumentCount()) == 3)) {
		return interpreterProxy->primitiveFail();
	}
	formOop = interpreterProxy->stackObjectValue(0);
	charIndex = interpreterProxy->stackIntegerValue(1);
	fontIndex = interpreterProxy->stackIntegerValue(2);
	if (interpreterProxy->failed()) {
		return null;
	}
	if (!((interpreterProxy->isPointers(formOop))
		 && ((interpreterProxy->slotSizeOf(formOop)) >= 4))) {
		return interpreterProxy->primitiveFail();
	}
	formBits = interpreterProxy->fetchPointerofObject(0, formOop);
	formWidth = interpreterProxy->fetchIntegerofObject(1, formOop);
	formHeight = interpreterProxy->fetchIntegerofObject(2, formOop);
	formDepth = interpreterProxy->fetchIntegerofObject(3, formOop);
	if (!((formWidth > 0)
		 && ((formHeight > 0)
 && (formDepth > 0)))) {
		return interpreterProxy->primitiveFail();
	}
	ppw = 32 / formDepth;
	pitch = ((formWidth + (ppw - 1)) / ppw) * 4;
	if (!(((interpreterProxy->fetchClassOf(formBits)) == (interpreterProxy->classBitmap()))
		 && ((interpreterProxy->byteSizeOf(formBits)) == (pitch * formHeight)))) {
		return interpreterProxy->primitiveFail();
	}
	formBits = ((int) (interpreterProxy->firstIndexableField(formBits)));
	if (!(ioFontGlyphOfChar(fontIndex, charIndex, formBits, formWidth, formHeight, formDepth))) {
		return interpreterProxy->primitiveFail();
	}
	return interpreterProxy->pop(3);
}

EXPORT(sqInt)
primitiveFontNumKernPairs(void) {
    sqInt fontIndex;
    sqInt nKernPairs;

	if (!((interpreterProxy->methodArgumentCount()) == 1)) {
		return interpreterProxy->primitiveFail();
	}
	fontIndex = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	nKernPairs = ioFontNumKernPairs(fontIndex);
	if (!(nKernPairs >= 0)) {
		return interpreterProxy->primitiveFail();
	}
	interpreterProxy->pop(2);
	return interpreterProxy->pushInteger(nKernPairs);
}

EXPORT(sqInt)
primitiveFontWidthOfChar(void) {
    sqInt charIndex;
    sqInt charWidth;
    sqInt fontIndex;

	if (!((interpreterProxy->methodArgumentCount()) == 2)) {
		return interpreterProxy->primitiveFail();
	}
	charIndex = interpreterProxy->stackIntegerValue(0);
	fontIndex = interpreterProxy->stackIntegerValue(1);
	if (interpreterProxy->failed()) {
		return null;
	}
	charWidth = ioFontWidthOfChar(fontIndex, charIndex);
	if (!(charWidth >= 0)) {
		return interpreterProxy->primitiveFail();
	}
	interpreterProxy->pop(3);
	return interpreterProxy->pushInteger(charWidth);
}

EXPORT(sqInt)
primitiveGetFontData(void) {
    sqInt buffer;
    char *bufPtr;
    sqInt bufSize;
    sqInt fontIndex;
    sqInt result;

	if (!((interpreterProxy->methodArgumentCount()) == 2)) {
		return interpreterProxy->primitiveFail();
	}
	buffer = interpreterProxy->stackObjectValue(0);
	fontIndex = interpreterProxy->stackIntegerValue(1);
	if (interpreterProxy->failed()) {
		return null;
	}
	if (!(interpreterProxy->isBytes(buffer))) {
		return interpreterProxy->primitiveFail();
	}
	bufSize = interpreterProxy->byteSizeOf(buffer);
	bufPtr = interpreterProxy->firstIndexableField(buffer);
	result = ioGetFontData(fontIndex, bufPtr, bufSize);
	interpreterProxy->pop(3);
	return interpreterProxy->pushInteger(result);
}

EXPORT(sqInt)
primitiveListFont(void) {
    sqInt fontIndex;
    char *fontName;
    sqInt fontNameLen;
    sqInt fontOop;
    char *fontPtr;
    sqInt i;

	if (!((interpreterProxy->methodArgumentCount()) == 1)) {
		return interpreterProxy->primitiveFail();
	}
	fontIndex = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	fontName = ioListFont(fontIndex);
	if (fontName == null) {
		interpreterProxy->pop(2);
		return interpreterProxy->push(interpreterProxy->nilObject());
	}
	fontNameLen = strlen(fontName);
	fontOop = interpreterProxy->instantiateClassindexableSize(interpreterProxy->classString(), fontNameLen);
	fontPtr = interpreterProxy->firstIndexableField(fontOop);
	for (i = 0; i <= (fontNameLen - 1); i += 1) {
		fontPtr[i] = (fontName[i]);
	}
	interpreterProxy->pop(2);
	interpreterProxy->push(fontOop);
}


/*	Note: This is coded so that is can be run from Squeak. */

EXPORT(sqInt)
setInterpreter(struct VirtualMachine*anInterpreter) {
    sqInt ok;

	interpreterProxy = anInterpreter;
	ok = interpreterProxy->majorVersion() == VM_PROXY_MAJOR;
	if (ok == 0) {
		return 0;
	}
	ok = interpreterProxy->minorVersion() >= VM_PROXY_MINOR;
	return ok;
}


/*	Shut down the module */

EXPORT(sqInt)
shutdownModule(void) {
	return ioFontShutdown();
}


#ifdef SQUEAK_BUILTIN_PLUGIN

void* NativeFontPlugin_exports[][3] = {
	{"NativeFontPlugin", "getModuleName", (void*)getModuleName},
	{"NativeFontPlugin", "initialiseModule", (void*)initialiseModule},
	{"NativeFontPlugin", "primitiveCreateFont", (void*)primitiveCreateFont},
	{"NativeFontPlugin", "primitiveDestroyFont", (void*)primitiveDestroyFont},
	{"NativeFontPlugin", "primitiveFontAscent", (void*)primitiveFontAscent},
	{"NativeFontPlugin", "primitiveFontDataSize", (void*)primitiveFontDataSize},
	{"NativeFontPlugin", "primitiveFontDescent", (void*)primitiveFontDescent},
	{"NativeFontPlugin", "primitiveFontEmbeddingFlags", (void*)primitiveFontEmbeddingFlags},
	{"NativeFontPlugin", "primitiveFontEncoding", (void*)primitiveFontEncoding},
	{"NativeFontPlugin", "primitiveFontFullWidthOfChar", (void*)primitiveFontFullWidthOfChar},
	{"NativeFontPlugin", "primitiveFontGetKernPair", (void*)primitiveFontGetKernPair},
	{"NativeFontPlugin", "primitiveFontGlyphOfChar", (void*)primitiveFontGlyphOfChar},
	{"NativeFontPlugin", "primitiveFontNumKernPairs", (void*)primitiveFontNumKernPairs},
	{"NativeFontPlugin", "primitiveFontWidthOfChar", (void*)primitiveFontWidthOfChar},
	{"NativeFontPlugin", "primitiveGetFontData", (void*)primitiveGetFontData},
	{"NativeFontPlugin", "primitiveListFont", (void*)primitiveListFont},
	{"NativeFontPlugin", "setInterpreter", (void*)setInterpreter},
	{"NativeFontPlugin", "shutdownModule", (void*)shutdownModule},
	{NULL, NULL, NULL}
};

#endif /* ifdef SQ_BUILTIN_PLUGIN */
