/* Automatically generated by
	CCodeGeneratorGlobalStructure VMMaker-eem.717 uuid: 98b71aa5-3304-4c7c-aae7-d0a442841f86
 */

#define COGVM 1
#if !defined(COGMTVM)
#	define COGMTVM 0
#endif
#define STACKVM 1
#define SQ_VI_BYTES_PER_WORD 4

#define PrimErrGenericFailure 1
#define PrimErrBadReceiver 2
#define PrimErrBadArgument 3
#define PrimErrBadIndex 4
#define PrimErrBadNumArgs 5
#define PrimErrInappropriate 6
#define PrimErrUnsupported 7
#define PrimErrNoModification 8
#define PrimErrNoMemory 9
#define PrimErrNoCMemory 10
#define PrimErrNotFound 11
#define PrimErrBadMethod 12
#define PrimErrNamedInternal 13
#define PrimErrObjectMayMove 14
#define PrimErrLimitExceeded 15

