#!/bin/bash

# include logging
# Set debugging off=FALSE, on=anything else
debug="TRUE"
utilsFile="/home/openqwaq/server/apps/scripts/qutils.sh"

if [ ! -f $utilsFile ]; then
  log() {
    msg=$1
    echo "${myDate}: ${msg}"
  }
else
  . $utilsFile
fi


log "#####################"
log "Executing qlaunch-qms"
log "Args are: $*"
log ""

# Make sure that a user and supported account-type are specified.

if [ "$QwaqRemoteAppUSER" = "" ]; then
    log "ERROR: must specify username via \$QwaqRemoteAppUSER"
    exit 1
fi
case "$QwaqRemoteAppUSERTYPE" in
    'REALM') USERNAME_PREFIX='QR-';;
    'FORUM') USERNAME_PREFIX='QF-';;
    *)
	log "qlaunch-qms.sh: invalid account type $QwaqRemoteAppUSERTYPE";
	exit 1 ;;
esac

HERE=`dirname $0`

# Ensure the chroot directory exists
Q_USERNAME=$USERNAME_PREFIX$QwaqRemoteAppUSER
CHROOT_DIR=$QwaqRemoteAppHOME

log "Q_USERNAME: ${USERNAME_PREFIX$QwaqRemoteAppUSER}"
log "QwaqRemoteAppHOME: ${QwaqRemoteAppHOME}"

run_me="run_me_`date +%Y%m%d-%H%M%s`"

rm -rf ${CHROOT_DIR}/${run_me} > /dev/null 2>&1

cat <<EOF>> ${CHROOT_DIR}/${run_me}
#!/bin/bash
# 
# Automatically generated by qlaunch

trap "" SIGTERM
trap "" SIGTSTP

export RUN_ME=${run_me}
export HOME=/sharedDocuments/forum
/bin/su openqwaq -c "/usr/bin/vncserver $* > ./tmp/${run_me} 2>&1"
rm -rf /${run_me}
EOF

chmod 775 ${CHROOT_DIR}/${run_me}

COMMAND="/${run_me}"

/usr/sbin/chroot ${CHROOT_DIR} ${COMMAND}

result=$?
if test $result -ne 0; then
    log "\nERROR: qlaunch-qms.sh: launch failed - $result \n"
    log "\nCOMMAND: ${COMMAND}"
    log "\n	Error is: $?"
    exit 1
fi
